import Head from "next/head";
import Layout from "@/components/layout/layout";
import { useState, useEffect } from "react";
import { useRouter } from "next/navigation";
import Card from "@/components/cards/new-card";
import { Services } from "@/services/search";

export async function getServerSideProps(context) {
  const { q } = context?.query;
  return {
    props: {
      q: q || null,
    },
  };
}

export default function Search({ q }) {
  const router = useRouter();
  const [searchQuery, setSearchQuery] = useState(q || "");
  const [list, setList] = useState([]);
  const [error, setError] = useState("");
  const [loader, setLoader] = useState(false);

  const handleSearchInputChange = (event) => {
    setSearchQuery(event.target.value);
  };
  const handleSearchSubmit = (event) => {
    event.preventDefault();
    router.push(`/search?q=${searchQuery}`);
  };

  const getList = (qVal) => {
    setLoader(true);
    Services.getSearch(qVal)
      .then((res) => {
        setList(res?.data?.results);
        setError("");
        setLoader(false);
      })
      .catch((err) => {
        setLoader(false);
        setError(
          err?.response?.data?.message
            ? err?.response?.data?.message
            : "Some Error Occured!!!"
        );
      });
  };

  useEffect(() => {
    getList(q);
    setSearchQuery(q);
  }, [q]);

  return (
    <>
      <Head>
        <title>The Movie Database (TMDB)</title>
        <meta
          name="description"
          content="Generated by create Gatik as a clone of The Movie Database (TMDB) "
        />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/vercel.svg" />
      </Head>
      <Layout>
        <main data-component="home-page">
          <section className="inner_content">
            <div className="background-image">
              <div className="content-wrap container">
                <div className="title">
                  <h2>Welcome to Search.</h2>
                  <h3>
                    Millions of movies, TV shows and people to discover. Explore
                    now.
                  </h3>
                </div>
                <div className="search">
                  <form
                    id="inner_search_form"
                    action="/search"
                    method="get"
                    accept-charset="utf-8"
                  >
                    <label>
                      <input
                        name="query"
                        type="text"
                        tabindex="1"
                        autocorrect="off"
                        autofill="off"
                        autocomplete="off"
                        spellcheck="false"
                        placeholder="Search for a movie, tv show, person......"
                        value={searchQuery}
                        onChange={handleSearchInputChange}
                      />
                    </label>
                    <input
                      type="submit"
                      value="Search"
                      onClick={handleSearchSubmit}
                    />
                  </form>
                </div>
              </div>
            </div>
          </section>

          <section className="container">
            {loader ? (
              <div className="d-flex justify-content-center my-4 min-vh-100">
                Loading.......
              </div>
            ) : (
              <div className="row my-4 min-vh-100">
                {list?.map((val) => (
                  <div className="col-12" key={val?.id}>
                    <Card data={val} />
                  </div>
                ))}
                {list?.length === 0 && (
                  <div className="d-flex justify-content-center">
                    There are no movies that matched your query.
                  </div>
                )}
                {error && (
                  <div className="d-flex justified-content-center">{error}</div>
                )}
              </div>
            )}
          </section>
        </main>
      </Layout>
    </>
  );
}
