import Head from "next/head";
import Layout from "@/components/layout/layout";
import { useState, useEffect } from "react";
import { useRouter } from "next/navigation";
import Card from "@/components/cards/card";

export async function getServerSideProps(context) {
  try {
    const { q } = context?.query;
    const res = await fetch(
      `https://api.themoviedb.org/3/search/movie?include_adult=false&language=en-US&page=1&query=${q}&api_key=26eb8fe0ea17478b691097b4e10c4ac9`
    );

    if (!res.ok) {
      throw new Error("Failed to fetch data from the server.");
    }

    const repo = await res.json();
    return {
      props: {
        data: repo || null,
        q: q || null,
        error: null,
      },
    };
  } catch (error) {
    console.error("Error in getServerSideProps:", error);
    return {
      props: {
        data: null,
        q: null,
        error: "An error occurred while fetching data.",
      },
    };
  }
}

export default function Search({ data, q, error }) {
  const router = useRouter();
  const [searchQuery, setSearchQuery] = useState("");
  const [list, setList] = useState([]);

  const handleSearchInputChange = (event) => {
    setSearchQuery(event.target.value);
  };
  const handleSearchSubmit = (event) => {
    event.preventDefault();
    router.push(`/search?q=${searchQuery}`);
  };

  useEffect(() => {
    setList(data?.results);
  }, [data]);

  return (
    <>
      <Head>
        <title>The Movie Database (TMDB)</title>
        <meta
          name="description"
          content="Generated by create Gatik as a clone of The Movie Database (TMDB) "
        />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/vercel.svg" />
      </Head>
      <Layout>
        <main data-component="home-page">
          <section className="inner_content">
            <div className="background-image">
              {console.log("data", data, list)}
              <div className="content-wrap container">
                <div className="title">
                  <h2>Welcome to Search.</h2>
                  <h3>
                    Millions of movies, TV shows and people to discover. Explore
                    now.
                  </h3>
                </div>
                <div className="search">
                  <form
                    id="inner_search_form"
                    action="/search"
                    method="get"
                    accept-charset="utf-8"
                  >
                    <label>
                      <input
                        name="query"
                        type="text"
                        tabindex="1"
                        autocorrect="off"
                        autofill="off"
                        autocomplete="off"
                        spellcheck="false"
                        placeholder="Search for a movie, tv show, person......"
                        value={searchQuery}
                        onChange={handleSearchInputChange}
                      />
                    </label>
                    <input
                      type="submit"
                      value="Search"
                      onClick={handleSearchSubmit}
                    />
                  </form>
                </div>
              </div>
            </div>
          </section>
          <section className="container">
            <div className="row my-4">
              {list?.map((val) => (
                <div className="col-12" key={val?.id}>
                  <Card data={val} />
                </div>
              ))}
              {list?.length === 0 && (
                <div className="d-flex justified-content-center">
                  There are no movies that matched your query.
                </div>
              )}
              {error && (
                <div className="d-flex justified-content-center">{error}</div>
              )}
            </div>
          </section>
        </main>
      </Layout>
    </>
  );
}
