import Head from "next/head";
import Layout from "@/components/layout/layout";
import { Router } from "next/router";
import { useState } from "react";

export default function Search() {
  const [searchQuery, setSearchQuery] = useState("");

  const handleSearchInputChange = (event) => {
    setSearchQuery(event.target.value);
  };
  const handleSearchSubmit = (event) => {
    event.preventDefault();
    Router.push(`/search?.query=${searchQuery}`);
  };
  return (
    <>
      <Head>
        <title>The Movie Database (TMDB)</title>
        <meta
          name="description"
          content="Generated by create Gatik as a clone of The Movie Database (TMDB) "
        />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/vercel.svg" />
      </Head>
      <Layout>
        <main data-component="home-page">
          <section className="inner_content">
            <div className="background-image">
              <div className="content-wrap container">
                <div className="title">
                  <h2>Welcome.</h2>
                  <h3>
                    Millions of movies, TV shows and people to discover. Explore
                    now.
                  </h3>
                </div>
                <div className="search">
                  <form
                    id="inner_search_form"
                    action="/search"
                    method="get"
                    accept-charset="utf-8"
                  >
                    <label>
                      <input
                        name="query"
                        type="text"
                        tabindex="1"
                        autocorrect="off"
                        autofill="off"
                        autocomplete="off"
                        spellcheck="false"
                        placeholder="Search for a movie, tv show, person......"
                        value={searchQuery}
                        onChange={handleSearchInputChange}
                      />
                    </label>
                    <input
                      type="submit"
                      value="Search"
                      onClick={handleSearchSubmit}
                    />
                  </form>
                </div>
              </div>
            </div>
          </section>
        </main>
      </Layout>
    </>
  );
}
